TTH_SETTING = {};
TTH_SETTING.global = {};
TTH_SETTING.global.teamUp = 0; -- 0是乱战也就是FFA, 1是所有AI结盟
TTH_SETTING.global.neutralTownLevel = 1; -- 中立城镇的建筑等级: 选择范围0~6, 默认为1, 0就是1级城建（议事堂）, 1就是6级城建（有政务厅/酒馆/市场/铁匠铺/1级魔法塔）, 每高一级多5级左右城建

TTH_SETTING.ai = {};
TTH_SETTING.ai.difficulty = {};
TTH_SETTING.ai.difficulty.dynamic = 0; -- 动态难度: 增兵系数前两周减半, 第五周开始每周*1.2, 特长-熟练20级生效, 特长-精通30级生效
TTH_SETTING.ai.difficulty.inferno = 0; -- 地狱难度: 该配置会令对AI的宝物配置失效
TTH_SETTING.ai.army = {};
TTH_SETTING.ai.army.coef = 1; -- 增兵系数
TTH_SETTING.ai.town = {};
TTH_SETTING.ai.town.grail = 0; -- 初始城镇是否有奇迹
TTH_SETTING.ai.town.level = 0; -- 城镇的建筑等级
TTH_SETTING.ai.hero = {};
TTH_SETTING.ai.hero.limit = 0; -- 可招募英雄数量: 0是无限制, 限制范围1~8
TTH_SETTING.ai.artifact = {};
TTH_SETTING.ai.artifact.travel = 0; -- 旅行者长靴
TTH_SETTING.ai.artifact.walking_dead = 0; -- 恶灵长靴
TTH_SETTING.ai.artifact.sentinel = 0; -- 哨兵之盾
TTH_SETTING.ai.artifact.heavenly = 0; -- 天启头盔
TTH_SETTING.ai.artifact.curse_shoulder = 0; -- 诅咒斗篷
TTH_SETTING.ai.artifact.draconic = 0; -- 龙神胸甲
TTH_SETTING.ai.artifact.angelic_alliance = 0; -- 天使联盟
TTH_SETTING.ai.artifact.eightfold = 0; -- 亚莎之八重杖
TTH_SETTING.ai.artifact.phoenix = 0; -- 大法师之典
TTH_SETTING.ai.artifact.book_of_malassa = 0; -- 玛拉萨之书
TTH_SETTING.ai.artifact.shackles_of_war = 0; -- 末日勇士桎梏
TTH_SETTING.ai.artifact.gem_of_phantom = 0; -- 幻影宝石
TTH_SETTING.ai.artifact.pendant_of_stardust = 0; -- 星尘坠饰
TTH_SETTING.ai.artifact.ring_of_haste = 0; -- 速度指环
TTH_SETTING.ai.skill = {};
TTH_SETTING.ai.skill.absolute = 0; -- 职业对应终极
TTH_SETTING.ai.talent = {};
TTH_SETTING.ai.talent.mastery = 0; -- 特长-熟练
TTH_SETTING.ai.talent.shantiri = 0; -- 特长-精通

TTH_SETTING.player = {};
TTH_SETTING.player.army = {};
TTH_SETTING.player.army.coef = 1; -- 增兵系数
TTH_SETTING.player.town = {};
TTH_SETTING.player.town.grail = 0; -- 初始城镇是否有奇迹
TTH_SETTING.player.town.level = 0; -- 城镇的建筑等级
TTH_SETTING.player.hero = {};
TTH_SETTING.player.hero.limit = 0; -- 可招募英雄数量: 0是无限制, 限制范围1~8
TTH_SETTING.player.artifact = {};
TTH_SETTING.player.artifact.travel = 0; -- 旅行者长靴
TTH_SETTING.player.artifact.walking_dead = 0; -- 恶灵长靴
TTH_SETTING.player.artifact.sentinel = 0; -- 哨兵之盾
TTH_SETTING.player.artifact.heavenly = 0; -- 天启头盔
TTH_SETTING.player.artifact.curse_shoulder = 0; -- 诅咒斗篷
TTH_SETTING.player.artifact.draconic = 0; -- 龙神胸甲
TTH_SETTING.player.artifact.angelic_alliance = 0; -- 天使联盟
TTH_SETTING.player.artifact.eightfold = 0; -- 亚莎之八重杖
TTH_SETTING.player.artifact.phoenix = 0; -- 大法师之典
TTH_SETTING.player.artifact.book_of_malassa = 0; -- 玛拉萨之书
TTH_SETTING.player.artifact.shackles_of_war = 0; -- 末日勇士桎梏
TTH_SETTING.player.artifact.gem_of_phantom = 0; -- 幻影宝石
TTH_SETTING.player.artifact.pendant_of_stardust = 0; -- 星尘坠饰
TTH_SETTING.player.artifact.ring_of_haste = 0; -- 速度指环
TTH_SETTING.player.skill = {};
TTH_SETTING.player.skill.absolute = 0; -- 职业对应终极
TTH_SETTING.player.talent = {};
TTH_SETTING.player.talent.mastery = 0; -- 特长-熟练
TTH_SETTING.player.talent.shantiri = 0; -- 特长-精通